TrialProj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('trialProj/', include('trialProjApp.urls')),
    path('admin/', admin.site.urls),
]

trialProjApp/urls.py
from django.urls import path

from . import views

app_name = 'trial_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:meter_id>/', views.detail, name='detail'),
    path('<str:meter_id>/deleteAll/', views.delete_all, name='deleteAll'),
    path('<str:meter_id>/uploadData/', views.upload_data, name='uploadData'),
    path('<str:meter_id>/download/', views.download_csv, name='downloadCSV'),
]

trialProjApp/models.py
from django.db import models

# Create your models here.


class Meter(models.Model):
    ELECTRICITY = 'E'
    GAS = 'G'
    WATER = 'W'
    RESOURCE_TYPE_CHOICES = [
        (ELECTRICITY, 'Electricity'),
        (GAS, 'Gas'),
        (WATER, 'Water'),
    ]
    name = models.CharField(primary_key=True, max_length=255, blank=False, null=False)
    resource_type = models.CharField(max_length=3, choices=RESOURCE_TYPE_CHOICES, default=ELECTRICITY)
    unit = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return str(self.name)


class MeterData(models.Model):
    date = models.DateField()
    value = models.FloatField()
    meter = models.ForeignKey(Meter, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)

trialProjApp/forms.py
from django import forms
from .models import Meter


class CreateForm(forms.ModelForm):
    ELECTRICITY = 'E'
    GAS = 'G'
    WATER = 'W'
    RESOURCE_TYPE_CHOICES = [
        (ELECTRICITY, 'Electricity'),
        (GAS, 'Gas'),
        (WATER, 'Water'),
    ]

    class Meta:
        model = Meter
        fields = ('name', 'unit', 'resource_type')

    name = forms.CharField(label='Enter name')
    resource_type = forms.ChoiceField(choices=RESOURCE_TYPE_CHOICES, required=True)
    unit = forms.CharField(label='Enter unit')
    name.widget.attrs.update({'class': 'form-control'})
    resource_type.widget.attrs.update({'class': 'form-control'})
    unit.widget.attrs.update({'class': 'form-control'})

trialProjApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import mimetypes
import os
import pandas as pd
from .models import Meter, MeterData
from .meterEntity import MeterEntity
from .forms import CreateForm
from .utils import validation, prepare_detail

# Create your views here.


def index(request):
    meters_list = Meter.objects.all()
    form = CreateForm()
    context = {'meters_list': meters_list, 'form': form}
    return render(request, 'trialProjApp/index.html', context)


def detail(request, meter_id):
    meter = get_object_or_404(Meter, pk=meter_id)
    meter_data_list = meter.meterdata_set.all().order_by('date')
    ready_data = prepare_detail(meter_data_list)
    ready_data['meter'] = meter
    return render(request, 'trialProjApp/detail.html', ready_data)


def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            entity = MeterEntity(form.cleaned_data['name'],
                                 form.cleaned_data['resource_type'],
                                 form.cleaned_data['unit'])
            try:
                entity.create_meter()
            except (KeyError, Meter.DoesNotExist):
                return render(request, 'trialProjApp/index.html', {'response': 'Oops, something went wrong!'})
            else:
                return HttpResponseRedirect(reverse('trial_app:index'))


def delete_all(request, meter_id):
    try:
        m = MeterEntity(meter_id)
        m.delete_all_data()
    except (KeyError, MeterData.DoesNotExist):
        return render(request, 'trialProjApp/index.html', {'response': 'Failure'})
    else:
        return HttpResponseRedirect(reverse('trial_app:detail', args=(meter_id,)))


def upload_data(request, meter_id):
    try:
        if request.method == 'POST' and request.FILES['file']:
            csv_file = pd.read_csv(request.FILES['file'])
            valid_response = validation(csv_file)
            if valid_response:
                return render(request, 'trialProjApp/index.html', {'response': valid_response})
            dat = []
            for line in request.FILES['file']:
                str_text = line.decode()
                dat.append(str_text)
            m = MeterEntity(name=meter_id)
            m.load_data(dat)
            if m.errors:
                return render(request, 'trialProjApp/index.html', {'response': m.errors})
    except Exception as e:
        return render(request, 'trialProjApp/index.html', {'response': 'Failure : %s' % e})
    else:
        return HttpResponseRedirect(reverse('trial_app:detail', args=(meter_id,)))


def download_csv(request, meter_id):
    meter = get_object_or_404(Meter, pk=meter_id)
    meter_data_list = meter.meterdata_set.all().order_by('date')
    ready_data = prepare_detail(meter_data_list)['dataTable']
    ready_data.to_csv('trialProjApp/downloads/currentCSV.csv', columns=['ABSOLUTE VALUE', 'DATE', 'RELATIVE VALUE'],
              index=False)
    fl_path = 'trialProjApp/downloads/currentCSV.csv'
    fp = open(fl_path, "rb")
    response = HttpResponse(fp.read())
    fp.close()
    file_type = mimetypes.guess_type(fl_path)
    if file_type is None:
        file_type = 'application/octet-stream'
    response['Content-Type'] = file_type
    response['Content-Length'] = str(os.stat(fl_path).st_size)
    response['Content-Disposition'] = "attachment; filename=currentCSV.csv"
    return response

trialProjApp/templates/trialProjApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Trial Project</title>
</head>
<body>
<!--   START HERE   -->
{% block content %}
{% endblock %}

<!--<span id="year"></span>-->
<script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());
</script>
</body>
</html>

trialProjApp/templates/trialProjApp/detail.html
{% extends 'trialProjApp/base.html' %}
{% block content %}

    <div class="container">
        <h1>{{ meter.name }}</h1>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Value</th>
                </tr>
                </thead>
                <tbody>
                {% for m in meterDataList %}
                    <tr>
                        <td>{{ m.date }}</td>
                        <td>{{ m.value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form action="{% url 'trial_app:uploadData' meter.name %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row my-3">
                    <div class="col-md-6">
                        <input type="text" name="meter_id" value="{{ meter.name }}" hidden>
                        <div class="custom-file">
                            <input class="form-control-file" type="file" id="file" name="file">
                            <label class="custom-file-label" for="file">Выберите файл</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-success text-white">
                            <i class="fa fa-upload" aria-hidden="true"></i> Upload File
                        </button>
                    </div>
                </div>
            </form>
            <a href="{% url 'trial_app:deleteAll' meter.name %}" class="btn btn-danger">Delete all</a>
            <a href="{% url 'trial_app:downloadCSV' meter.name %}" class="btn btn-warning">Download CSV</a>
        </div>
    </div>
    <figure class="highcharts-figure">
        <div class="containerChart"></div>
    </figure>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script>
        var container = document.createElement('div');
        document.body.appendChild(container);


        window.chart = new Highcharts.Chart({
            chart: {
                renderTo: container,
                height: 400
            },
            title: {
                text: 'Infographics for {{ meter.name }}'
            },

            yAxis: {
                title: {
                    text: 'Values'
                }
            },

            xAxis: {
                type: 'datetime',
                labels: {
                    formatter: function () {
                        return Highcharts.dateFormat('%b %Y', this.value);
                    },
                    title:{
                        text: 'Duration'
                    }
                },
                    categories: {{ yRangeSet }}
                },

                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle'
                },

                series: [{
                    name: '{{meter.name}}',
                    data: {{ xValues }}
                }],

                responsive: {
                    rules: [{
                        condition: {
                            maxWidth: 500
                        },
                        chartOptions: {
                            legend: {
                                layout: 'horizontal',
                                align: 'center',
                                verticalAlign: 'bottom'
                            }
                        }
                    }]
                }
            });
    </script>

{% endblock %}

trialProjApp/templates/trialProjApp/index.html
{% extends 'trialProjApp/base.html' %}

{% block content %}

    {% if meters_list %}
        <div class="container">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Resource Type</th>
                    <th>Unit</th>
                </tr>
                </thead>
                <tbody>
                {% for meter in meters_list %}
                    <tr>
                        <td><a href="{% url 'trial_app:detail' meter.name %}">{{ meter.name }}</a></td>
                        <td>{{ meter.resource_type }}</td>
                        <td>{{ meter.unit }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    {% elif response %}
        <div class="container">
            <div class="alert alert-danger">
                <strong>Message:</strong> {{ response }}
            </div>
            <a href="{% url 'trial_app:index' %}" class="btn btn-secondary">Restart Page...</a>
        </div>
    {% else %}
        <div class="container">
            <div class="alert alert-warning">
                <strong>No meters are available.</strong>
            </div>
        </div>
    {% endif %}
    <div class="container">
        <button class="btn btn-primary mr-0" data-toggle="modal" data-target="#createModal">Add Meter</button>
    </div>


    <div id="createModal" class="modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create Meter</h5>
                    <button class="close" data-dismiss="modal">×</button>
                </div>
                <form action="{% url 'trial_app:create' %}" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        {{ form }}
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Add meter" class="btn btn-secondary">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}